import React, { useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, BarChart3, Calendar, ChevronLeft, ChevronRight, CircleDollarSign, CreditCard, DollarSign, Eye, Hash, Loader2, MapPin, Package, Phone, Search, ShoppingCart, Trash2, TrendingUp, Users, X } from 'lucide-react';
import { Card } from '../../../components/ui/Card';
import { Button } from '../../../components/ui/Button';
import { PageHeader } from '../../../components/layout/PageHeader';
import { customerService } from '../services/customer.service';
import type { Expense, Payment, Product, PurchasePlan, Sale, StoreUser, StoreUsersResponse } from '../types/store';
import type { Customer, CustomerStore } from '../types/customer';
import { toast } from 'react-hot-toast';

type Tab = 'products' | 'sales' | 'purchases' | 'expenses' | 'users' | 'payments';
type Row = Product | Sale | PurchasePlan | Expense | StoreUser | Payment;
type NavState = { userId?: string; storeData?: CustomerStore; customerData?: Customer };
const TABS: { id: Tab; icon: React.ElementType }[] = [
  { id: 'products', icon: Package }, { id: 'sales', icon: TrendingUp },
  { id: 'purchases', icon: ShoppingCart }, { id: 'expenses', icon: DollarSign },
  { id: 'users', icon: Users }, { id: 'payments', icon: CreditCard },
];
const label = (key: string) => key.replace(/([a-z0-9])([A-Z])/g, '$1 $2').replace(/_/g, ' ').replace(/^./, c => c.toUpperCase());
const value = (item: unknown): React.ReactNode => item == null || item === '' ? 'N/A' : typeof item === 'boolean' ? (item ? 'Yes' : 'No') : String(item);
type Tone = 'success' | 'warning' | 'danger' | 'gray' | 'primary';
const TONE_CLASSES: Record<Tone, string> = { success: 'bg-success-100 text-success-800', warning: 'bg-warning-100 text-warning-800', danger: 'bg-danger-100 text-danger-800', gray: 'bg-gray-100 text-gray-700', primary: 'bg-primary-100 text-primary-800' };
const toneFor = (status?: string): Tone => { const s = (status || '').toUpperCase(); if (['COMPLETED', 'PAID', 'APPROVED', 'IN_STOCK', 'SUCCESS'].some(k => s.includes(k))) return 'success'; if (['PENDING', 'PROCESSING', 'LOW_STOCK', 'DRAFT', 'QUOTATION'].some(k => s.includes(k))) return 'warning'; if (['CANCELLED', 'FAILED', 'OUT_OF_STOCK', 'INACTIVE', 'REJECTED', 'EXPIRED'].some(k => s.includes(k))) return 'danger'; return 'gray'; };
const Badge = ({ text, tone }: { text: string; tone: Tone }) => <span className={`inline-flex items-center whitespace-nowrap rounded-full px-2.5 py-0.5 text-xs font-medium ${TONE_CLASSES[tone]}`}>{text}</span>;

const Pager = ({ page, total, size, change, changeSize }: { page: number; total: number; size: number; change: (n: number) => void; changeSize: (n: number) => void }) => {
  const pages = Math.max(1, Math.ceil(total / size));
  const pageNumbers = Array.from({ length: pages }, (_, index) => index).filter(index => index === 0 || index === pages - 1 || Math.abs(index - page) <= 1);
  return <div className="flex flex-col gap-4 border-t border-gray-200 bg-gray-50/60 px-4 py-3 lg:flex-row lg:items-center lg:justify-between">
    <div className="flex flex-wrap items-center gap-4"><span className="text-sm text-gray-600">Showing <b className="text-gray-900">{total ? page * size + 1 : 0}–{Math.min(total, (page + 1) * size)}</b> of <b className="text-gray-900">{total}</b></span><label className="flex items-center gap-2 text-sm text-gray-600">Rows per page<select value={size} onChange={event => changeSize(Number(event.target.value))} className="rounded-md border-gray-300 py-1 pl-2 pr-7 text-sm focus:border-primary-500 focus:ring-primary-500"><option value="5">5</option><option value="10">10</option><option value="20">20</option><option value="50">50</option></select></label></div>
    <div className="flex items-center gap-1"><button className="rounded-md border bg-white p-2 text-gray-600 hover:border-primary-300 hover:text-primary-700 disabled:opacity-40" disabled={!page} onClick={() => change(page - 1)} aria-label="Previous page"><ChevronLeft className="h-4 w-4" /></button>{pageNumbers.map((number, index) => <React.Fragment key={number}>{index > 0 && number - pageNumbers[index - 1] > 1 && <span className="px-1 text-gray-400">…</span>}<button onClick={() => change(number)} className={`h-9 min-w-9 rounded-md px-2 text-sm font-medium ${number === page ? 'bg-primary-600 text-white' : 'border bg-white text-gray-600 hover:border-primary-300 hover:text-primary-700'}`}>{number + 1}</button></React.Fragment>)}<button className="rounded-md border bg-white p-2 text-gray-600 hover:border-primary-300 hover:text-primary-700 disabled:opacity-40" disabled={page + 1 >= pages} onClick={() => change(page + 1)} aria-label="Next page"><ChevronRight className="h-4 w-4" /></button></div>
  </div>;
};

const Details = ({ row, tab, close, adjust, remove }: { row: Row; tab: Tab; close: () => void; adjust: (p: Product, n: number) => void; remove: (p: Product) => void }) => {
  const product = tab === 'products' ? row as Product : null;
  const sale = tab === 'sales' ? row as Sale : null;
  const [stock, setStock] = useState(product?.stockDetails.quantity || 0);
  const money = (amount: number) => new Intl.NumberFormat('en-TZ', { style: 'currency', currency: 'TZS', maximumFractionDigits: 0 }).format(amount || 0);
  const productData = product as (Product & { stockMovements?: Record<string, unknown>[]; movements?: Record<string, unknown>[]; stockHistory?: Record<string, unknown>[] }) | null;
  const movements = productData?.recentStockMovements || productData?.stockMovements || productData?.movements || productData?.stockHistory || [];
  const nested = Object.entries(row).filter(([, item]) => typeof item === 'object' && item !== null);
  const basics = Object.entries(row).filter(([, item]) => typeof item !== 'object' || item === null);
  const renderNested = (item: unknown) => {
    if (Array.isArray(item)) {
      if (!item.length) return <p className="py-5 text-center text-sm text-gray-500">No records available</p>;
      const keys = Array.from(new Set(item.flatMap(entry => typeof entry === 'object' && entry ? Object.keys(entry) : [])));
      return <div className="max-h-64 overflow-auto rounded-lg border"><table className="min-w-full divide-y divide-gray-200 text-sm"><thead className="sticky top-0 bg-gray-50"><tr>{keys.map(key => <th key={key} className="whitespace-nowrap px-3 py-2 text-left text-xs font-semibold uppercase text-gray-500">{label(key)}</th>)}</tr></thead><tbody className="divide-y bg-white">{item.map((entry, index) => <tr key={index}>{keys.map(key => <td key={key} className="whitespace-nowrap px-3 py-2 text-gray-700">{value((entry as Record<string, unknown>)[key])}</td>)}</tr>)}</tbody></table></div>;
    }
    return <dl className="grid gap-x-6 gap-y-4 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(item as Record<string, unknown>).map(([key, entryValue]) => <div key={key}><dt className="text-xs font-medium text-gray-500">{label(key)}</dt><dd className="mt-1 break-words text-sm font-medium text-gray-900">{value(entryValue)}</dd></div>)}</dl>;
  };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onMouseDown={close}>
    <div className="max-h-[90vh] w-full max-w-5xl overflow-y-auto rounded-xl bg-white shadow-2xl" onMouseDown={e => e.stopPropagation()}>
      <div className="sticky top-0 z-20 flex items-center justify-between border-b border-primary-100 bg-primary-50 px-6 py-4"><div><div className="mb-1 h-1 w-10 rounded-full bg-primary-500" /><h2 className="text-lg font-semibold text-gray-900">{product?.productName || (sale ? `Sale ${sale.saleNumber}` : `${label(tab.slice(0, -1))} details`)}</h2><p className="mt-0.5 text-sm text-gray-500">{product?.productCode || sale?.customerName || 'Complete record information'}</p></div><button onClick={close} className="rounded-lg p-2 text-gray-500 hover:bg-primary-100 hover:text-primary-700"><X className="h-5 w-5" /></button></div>
      {product ? <div className="space-y-5 p-6">
        <div className="grid divide-y rounded-lg border border-primary-100 bg-primary-50/40 sm:grid-cols-4 sm:divide-x sm:divide-y-0">{[['Current stock', product.stockDetails.quantity], ['Selling price', money(product.sellingPrice)], ['Cost price', money(product.costPrice)], ['Gross margin', money(product.sellingPrice - product.costPrice)]].map(([title, metric]) => <div key={String(title)} className="p-4"><div className="text-xs font-medium text-gray-500">{title}</div><div className="mt-1 text-lg font-semibold text-gray-900">{metric}</div></div>)}</div>
        <div className="grid gap-5 lg:grid-cols-3"><section className="rounded-lg border p-5 lg:col-span-2"><h3 className="mb-4 text-sm font-semibold text-gray-900">Product information</h3><dl className="grid gap-x-6 gap-y-4 sm:grid-cols-2">{basics.map(([key, item]) => <div key={key}><dt className="text-xs text-gray-500">{label(key)}</dt><dd className="mt-1 break-words text-sm font-medium text-gray-900">{value(item)}</dd></div>)}</dl></section><section className="rounded-lg border p-5"><h3 className="mb-4 text-sm font-semibold">Inventory status</h3><Badge text={product.stockDetails.isOutOfStock ? 'Out of stock' : product.stockDetails.isLowStock ? 'Low stock' : 'In stock'} tone={product.stockDetails.isOutOfStock ? 'danger' : product.stockDetails.isLowStock ? 'warning' : 'success'} /><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-gray-500">Reorder level</dt><dd className="font-medium">{product.reorderLevel ?? product.stockDetails.minAlert ?? 'N/A'}</dd></div><div className="flex justify-between"><dt className="text-gray-500">Tracked</dt><dd className="font-medium">{product.isTrackedInventory ? 'Yes' : 'No'}</dd></div><div className="flex justify-between"><dt className="text-gray-500">Last updated</dt><dd className="font-medium">{new Date(product.stockDetails.lastUpdatedAt).toLocaleDateString()}</dd></div></dl></section></div>
        <section className="rounded-lg border p-5"><div className="mb-4 flex items-center justify-between"><div><h3 className="text-sm font-semibold">Recent stock movements</h3><p className="mt-1 text-xs text-gray-500">Inventory additions, reductions and adjustments</p></div><span className="rounded-full bg-primary-50 px-2.5 py-1 text-xs font-medium text-primary-700">{movements.length} records</span></div>{movements.length ? <div className="max-h-64 overflow-auto rounded-lg border"><table className="min-w-full divide-y divide-gray-200"><thead className="sticky top-0 bg-gray-50"><tr><th className="px-4 py-2.5 text-left text-xs font-semibold uppercase text-gray-500">Type</th><th className="px-4 py-2.5 text-right text-xs font-semibold uppercase text-gray-500">Quantity</th><th className="px-4 py-2.5 text-left text-xs font-semibold uppercase text-gray-500">Reason</th><th className="px-4 py-2.5 text-left text-xs font-semibold uppercase text-gray-500">Date</th></tr></thead><tbody className="divide-y bg-white">{movements.map((movement, index) => { const item = movement as Record<string, unknown>; const type = String(item.movementType || item.type || 'N/A').toUpperCase(); return <tr key={String(item.id || index)}><td className="px-4 py-3"><Badge text={type} tone={type === 'IN' ? 'success' : type === 'OUT' ? 'danger' : 'primary'} /></td><td className={`px-4 py-3 text-right text-sm font-semibold ${type === 'IN' ? 'text-success-700' : type === 'OUT' ? 'text-danger-700' : 'text-gray-900'}`}>{type === 'IN' ? '+' : type === 'OUT' ? '−' : ''}{String(item.quantity ?? 0)}</td><td className="px-4 py-3 text-sm text-gray-700">{value(item.reason)}</td><td className="whitespace-nowrap px-4 py-3 text-sm text-gray-500">{item.createdAt ? new Date(String(item.createdAt)).toLocaleString() : 'N/A'}</td></tr>; })}</tbody></table></div> : <div className="rounded-lg border border-dashed bg-gray-50 py-8 text-center text-sm text-gray-500">No recent stock movements available for this product.</div>}</section>
      </div> : <div className="space-y-5 p-6"><section className="rounded-lg border p-5"><h3 className="mb-4 text-sm font-semibold text-gray-900">Overview</h3><dl className="grid gap-x-6 gap-y-4 sm:grid-cols-2 lg:grid-cols-4">{basics.map(([key, item]) => <div key={key}><dt className="text-xs text-gray-500">{label(key)}</dt><dd className="mt-1 break-words text-sm font-medium text-gray-900">{value(item)}</dd></div>)}</dl></section>{nested.map(([key, item]) => <section key={key} className="rounded-lg border p-5"><div className="mb-4 flex items-center justify-between"><h3 className="text-sm font-semibold text-gray-900">{label(key)}</h3>{Array.isArray(item) && <span className="text-xs text-gray-500">{item.length} items</span>}</div>{renderNested(item)}</section>)}</div>}
      <div className="sticky bottom-0 flex flex-wrap items-center justify-end gap-3 border-t border-primary-100 bg-primary-50/70 p-5">{product && <><label className="flex items-center gap-2 text-sm font-medium text-gray-700">Stock <input type="number" min="0" step="0.01" value={stock} onChange={e => setStock(Number(e.target.value))} className="w-28 rounded-lg border-primary-200 focus:border-primary-500 focus:ring-primary-500" /></label><Button onClick={() => adjust(product, stock)}>Adjust inventory</Button><Button variant="secondary" className="text-red-700" onClick={() => remove(product)}><Trash2 className="mr-2 h-4 w-4" />Delete product</Button></>}<Button variant="secondary" onClick={close}>Close</Button></div>
    </div>
  </div>;
};

export const StoreDetailsPageEnhanced: React.FC = () => {
  const { storeId } = useParams<{ storeId: string }>();
  const navigate = useNavigate();
  const nav = (useLocation().state || {}) as NavState;
  const [store, setStore] = useState<StoreUsersResponse | null>(null);
  const [tab, setTab] = useState<Tab>('products');
  const [rows, setRows] = useState<Partial<Record<Tab, Row[]>>>({});
  const [loaded, setLoaded] = useState<Partial<Record<Tab, boolean>>>({});
  const [loadingTabs, setLoadingTabs] = useState<Tab[]>([]);
  const [query, setQuery] = useState('');
  const [page, setPage] = useState(0);
  const [pageSize, setPageSize] = useState(10);
  const [selected, setSelected] = useState<Row | null>(null);
  const [saleType, setSaleType] = useState<'DIRECT' | 'QUOTATION'>('DIRECT');
  const [salesDateFrom, setSalesDateFrom] = useState(() => new Date().toLocaleDateString('en-CA'));
  const [salesDateTo, setSalesDateTo] = useState(() => new Date().toLocaleDateString('en-CA'));

  useEffect(() => { if (!storeId) return; void (async () => {
    if (nav.storeData) { const s = nav.storeData; setStore({ store_id: s.store_id, store_number: s.store_number, store_name: s.store_name, store_code: `STORE-${s.store_number}`, store_location: s.store_location, staff_phone_number: s.staff_phone_number, store_description: s.store_description, created_at: s.created_at, total_users: 0, is_active: true, users: [] }); }
    else setStore(await customerService.getStoreDetails(storeId));
  })(); }, [storeId, nav.storeData]);

  const load = async (active: Tab, force = false) => {
    if (!storeId || (loaded[active] && !force)) return;
    setLoadingTabs(current => current.includes(active) ? current : [...current, active]);
    try {
      let data: Row[] = [];
      if (active === 'products') data = (await customerService.getStoreProducts(storeId, 0, 500))?.content || [];
      if (active === 'sales') data = (await customerService.getStoreSales(storeId, saleType, 0, 500, salesDateFrom, salesDateTo))?.content || [];
      if (active === 'purchases') data = (await customerService.getStorePurchasePlans(storeId, 0, 500))?.content || [];
      if (active === 'expenses') data = (await customerService.getStoreExpenses(storeId))?.items || [];
      if (active === 'users') { const response = await customerService.getStoreUsers(storeId); data = response?.users || []; if (response) setStore(current => current ? { ...current, users: response.users, total_users: response.total_users } : response); }
      if (active === 'payments' && nav.userId) data = (await customerService.getUserPayments(nav.userId)) || [];
      setRows(current => ({ ...current, [active]: data })); setLoaded(current => ({ ...current, [active]: true }));
    } catch (error) { console.error(error); toast.error(`Failed to load ${active}`); } finally { setLoadingTabs(current => current.filter(item => item !== active)); }
  };
  useEffect(() => { void load(tab); }, [tab, storeId]);
  useEffect(() => { if (!storeId) return; void Promise.all((['products', 'sales', 'purchases', 'users'] as Tab[]).map(item => load(item))); }, [storeId]);
  useEffect(() => { if (tab === 'sales' && loaded.sales) void load('sales', true); }, [saleType]);
  useEffect(() => { if (loaded.sales) void load('sales', true); }, [salesDateFrom, salesDateTo]);
  useEffect(() => setPage(0), [tab, query, salesDateFrom, salesDateTo, pageSize]);

  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return (rows[tab] || []).filter(row => { const saleDay = String((row as Sale).saleDate || '').slice(0, 10); const matchesDate = tab !== 'sales' || (saleDay >= salesDateFrom && saleDay <= salesDateTo); return matchesDate && (!q || JSON.stringify(row).toLowerCase().includes(q)); }); }, [rows, tab, query, salesDateFrom, salesDateTo]);
  const paged = filtered.slice(page * pageSize, (page + 1) * pageSize);
  const currency = (n: number) => new Intl.NumberFormat('en-TZ', { style: 'currency', currency: 'TZS', maximumFractionDigits: 0 }).format(n || 0);
  const date = (s?: string) => s ? new Date(s).toLocaleDateString() : 'N/A';
  const headings: Record<Tab, string[]> = { products: ['Code', 'Product', 'Brand', 'Selling price', 'Cost price', 'Stock', 'Status'], sales: ['Sale number', 'Customer', 'Status', 'Items', 'Total', 'Payment', 'Date'], purchases: ['Plan', 'Description', 'Type', 'Status', 'Items', 'Estimated', 'Actual'], expenses: ['Number', 'Category', 'Description', 'Amount', 'Notes', 'Date'], users: ['Full name', 'Phone', 'Email', 'Role', 'Status', 'Added'], payments: ['Reference', 'Plan', 'Amount', 'Mobile', 'Method', 'Status', 'Initiated'] };
  const cells = (row: Row): React.ReactNode[] => {
    if (tab === 'products') { const x = row as Product; const stockLabel = x.stockDetails.isOutOfStock ? 'Out of stock' : x.stockDetails.isLowStock ? 'Low stock' : 'In stock'; return [x.productCode, x.productName, x.brand, currency(x.sellingPrice), currency(x.costPrice), x.stockDetails.quantity, <Badge key="status" text={stockLabel} tone={x.stockDetails.isOutOfStock ? 'danger' : x.stockDetails.isLowStock ? 'warning' : 'success'} />]; }
    if (tab === 'sales') { const x = row as Sale; return [x.saleNumber, x.customerName || 'Walk-in', <Badge key="status" text={x.saleStatus} tone={toneFor(x.saleStatus)} />, x.totalItems, currency(x.totalAmount), x.paymentMethod, date(x.saleDate)]; }
    if (tab === 'purchases') { const x = row as PurchasePlan; return [x.planName, x.description, x.purchaseType, <Badge key="status" text={x.status} tone={toneFor(x.status)} />, x.totalItems, currency(x.totalEstimatedCost), currency(x.totalActualCost)]; }
    if (tab === 'expenses') { const x = row as Expense; return [x.expenseNumber, x.category, x.description, currency(x.amount), x.notes || 'N/A', date(x.expenseDate)]; }
    if (tab === 'users') { const x = row as StoreUser; return [x.fullName, x.phoneNumber, x.email || 'N/A', x.role, <Badge key="status" text={x.isActive ? 'Active' : 'Inactive'} tone={x.isActive ? 'success' : 'gray'} />, date(x.addedAt)]; }
    const x = row as Payment; return [x.paymentReference, x.planName, `${currency(x.amount)} ${x.currency}`, x.mobileNumber, x.paymentMethod, <Badge key="status" text={x.status} tone={toneFor(x.status)} />, date(x.initiatedAt)];
  };
  const back = () => { const phone = nav.customerData?.phone_number; navigate(phone ? `/customer-support?phone=${encodeURIComponent(phone)}` : '/customer-support', { state: { customerData: nav.customerData }, replace: true }); };
  const adjust = (product: Product, quantity: number) => { if (!Number.isFinite(quantity) || quantity < 0) return toast.error('Enter a valid quantity'); const threshold = product.reorderLevel ?? product.stockDetails.minAlert ?? 0; setRows(current => ({ ...current, products: (current.products || []).map(row => row === product ? { ...product, stockDetails: { ...product.stockDetails, quantity, isOutOfStock: quantity === 0, isLowStock: quantity > 0 && quantity <= threshold, isInStock: quantity > threshold, lastUpdatedAt: new Date().toISOString() } } : row) })); setSelected(null); toast.success('Inventory updated in this view'); };
  const remove = (product: Product) => { if (!window.confirm(`Delete ${product.productName} from this view?`)) return; setRows(current => ({ ...current, products: (current.products || []).filter(row => row !== product) })); setSelected(null); toast.success('Product removed from this view'); };
  const totalSales = (rows.sales || []).reduce((sum, item) => sum + (item as Sale).totalAmount, 0);
  const totalPurchases = (rows.purchases || []).reduce((sum, item) => sum + (item as PurchasePlan).totalActualCost, 0);
  const lowStock = (rows.products || []).filter(item => (item as Product).stockDetails.isLowStock || (item as Product).stockDetails.isOutOfStock).length;
  const loading = loadingTabs.includes(tab);

  return <>
    <PageHeader title="Store Details" description="Store information, activity and management" icon={BarChart3}><Button onClick={back} variant="ghost" size="sm"><ArrowLeft className="mr-2 h-4 w-4" />Back to customer details</Button></PageHeader>
    <div className="min-h-screen space-y-6 bg-gradient-to-b from-primary-50/40 via-white to-white px-2 py-8">
      {store ? <Card className="overflow-hidden border border-primary-100 border-l-4 border-l-primary-500 p-0 shadow-sm animate-fade-in"><div className="border-b border-primary-100 bg-gradient-to-r from-primary-50 to-white p-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-2xl font-semibold text-gray-900">{store.store_name}</h2><Badge text={store.is_active === false ? 'Inactive' : 'Active'} tone={store.is_active === false ? 'danger' : 'success'} /></div><p className="mt-1 text-sm text-gray-500">{store.store_description || 'Store management and operations centre'}</p></div><div className="rounded-lg border border-primary-100 bg-white px-4 py-2 text-left shadow-sm md:text-right"><div className="text-xs font-medium uppercase tracking-wide text-gray-500">Store number</div><div className="mt-1 text-lg font-semibold text-primary-700">#{store.store_number}</div></div></div></div><dl className="grid divide-y bg-white sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-5">{[[Hash, 'Store ID', store.store_id], [Hash, 'Store code', store.store_code], [MapPin, 'Location', store.store_location], [Phone, 'Contact', store.staff_phone_number || 'N/A'], [Calendar, 'Created', date(store.created_at)]].map(([Icon, title, info]) => <div key={String(title)} className="flex min-w-0 items-start gap-3 p-4"><div className="rounded-md bg-primary-50 p-1.5"><Icon className="h-4 w-4 shrink-0 text-primary-600" /></div><div className="min-w-0"><dt className="text-xs font-medium text-gray-500">{title as React.ReactNode}</dt><dd className="mt-1 truncate text-sm font-medium text-gray-900" title={String(info)}>{info as React.ReactNode}</dd></div></div>)}</dl></Card> : <Card className="flex h-40 items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-primary-600" /></Card>}
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
        [CircleDollarSign, 'Total sales', currency(totalSales), `${(rows.sales || []).length} transactions`, 'bg-primary-50 text-primary-700'],
        [Package, 'Products', String((rows.products || []).length), lowStock ? `${lowStock} need attention` : 'All well stocked', lowStock ? 'bg-warning-100 text-warning-700' : 'bg-primary-50 text-primary-700'],
        [ShoppingCart, 'Purchases', currency(totalPurchases), `${(rows.purchases || []).length} purchase plans`, 'bg-success-100 text-success-700'],
        [Users, 'Team members', String((rows.users || []).length), 'Store access users', 'bg-primary-100 text-primary-800'],
      ].map(([Icon, title, metric, note, chip]) => <Card key={String(title)} className="border border-gray-200 p-5 shadow-sm transition-all duration-200 hover:-translate-y-0.5 hover:shadow-medium"><div className="flex items-start justify-between"><div><div className="text-sm font-medium text-gray-500">{title as React.ReactNode}</div><div className="mt-2 text-2xl font-semibold text-gray-900">{metric as React.ReactNode}</div><div className={`mt-1 text-xs font-medium ${lowStock && title === 'Products' ? 'text-warning-600' : 'text-gray-500'}`}>{note as React.ReactNode}</div></div><div className={`rounded-lg p-2.5 ${chip}`}><Icon className="h-5 w-5" /></div></div></Card>)}</div>
      <Card className="overflow-hidden border border-gray-200 shadow-sm"><nav className="flex overflow-x-auto border-b bg-white px-4">{TABS.map(({ id, icon: Icon }) => { const isTabLoading = loadingTabs.includes(id); return <button key={id} onClick={() => setTab(id)} disabled={isTabLoading && tab === id} className={`flex items-center gap-2 whitespace-nowrap border-b-2 px-4 py-4 text-sm font-medium transition-colors ${tab === id ? 'border-primary-500 bg-primary-50/60 text-primary-700' : 'border-transparent text-gray-500 hover:bg-gray-50 hover:text-gray-800'}`}>{isTabLoading ? <Loader2 className="h-4 w-4 animate-spin text-primary-600" /> : <Icon className="h-4 w-4" />}{label(id)}{isTabLoading && <span className="sr-only"> loading</span>}</button>; })}</nav>
        <div className="p-5"><div className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><h3 className="text-xl font-bold capitalize">{tab}</h3><p className="text-sm text-gray-500">{tab === 'sales' ? `${filtered.length} sales from ${date(salesDateFrom)} to ${date(salesDateTo)}` : `${filtered.length} matching items`}</p></div><div className="flex flex-col gap-2 sm:flex-row">{tab === 'sales' && <><label className="text-xs font-medium text-gray-600">Sale type<select value={saleType} onChange={e => setSaleType(e.target.value as 'DIRECT' | 'QUOTATION')} className="mt-1 block w-full rounded-lg border-gray-300 text-sm focus:border-primary-500 focus:ring-primary-500"><option value="DIRECT">Direct sales</option><option value="QUOTATION">Quotations</option></select></label><label className="text-xs font-medium text-gray-600">From<div className="relative mt-1"><Calendar className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input type="date" value={salesDateFrom} max={salesDateTo} onChange={e => setSalesDateFrom(e.target.value)} className="rounded-lg border-gray-300 py-2 pl-9 text-sm focus:border-primary-500 focus:ring-primary-500" /></div></label><label className="text-xs font-medium text-gray-600">To<div className="relative mt-1"><Calendar className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input type="date" value={salesDateTo} min={salesDateFrom} onChange={e => setSalesDateTo(e.target.value)} className="rounded-lg border-gray-300 py-2 pl-9 text-sm focus:border-primary-500 focus:ring-primary-500" /></div></label></>}<div className="relative min-w-64 self-end"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder={`Filter ${tab} as you type...`} className="w-full rounded-lg border-gray-300 py-2 pl-9 pr-3 text-sm focus:border-primary-500 focus:ring-primary-500" /></div></div></div>
          {loading ? <div className="flex h-64 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-primary-600" /></div> : <div className="overflow-hidden rounded-lg border"><div className="overflow-x-auto"><table className="min-w-full divide-y"><thead className="bg-gray-50"><tr>{headings[tab].map(h => <th key={h} className="px-4 py-3 text-left text-xs font-semibold uppercase text-gray-600">{h}</th>)}<th className="px-4 py-3 text-xs font-semibold uppercase text-gray-600">Action</th></tr></thead><tbody className="divide-y">{paged.map((row, i) => <tr key={(row as { id?: string; userId?: string }).id || (row as StoreUser).userId || i} className="transition-colors hover:bg-primary-50/40">{cells(row).map((cell, j) => <td key={j} className="max-w-xs truncate whitespace-nowrap px-4 py-3 text-sm text-gray-700">{cell}</td>)}<td className="px-4 py-3 text-center"><Button variant="ghost" size="sm" onClick={() => setSelected(row)} title="View details and actions"><Eye className="h-4 w-4" /></Button></td></tr>)}{!paged.length && <tr><td colSpan={headings[tab].length + 1} className="p-12 text-center text-gray-500"><div className="flex flex-col items-center gap-2"><Search className="h-8 w-8 text-gray-300" />No {tab} match your search.</div></td></tr>}</tbody></table></div><Pager page={page} total={filtered.length} size={pageSize} change={setPage} changeSize={setPageSize} /></div>}
        </div>
      </Card>
    </div>
    {selected && <Details row={selected} tab={tab} close={() => setSelected(null)} adjust={adjust} remove={remove} />}
  </>;
};
